fixup! [op][upsable][css][spatial_nav] CSS3 navigation implementation
:Release Notes:
Fix build error about StyleNavigationIndex.

:Detailed Notes:
It looks like we should use base::RefCounted(with explicit namespace)
or WTF RefCounted inside blink namespace. But StyleNavigationIndex
uses base::RefCounted without namespace. So change to use WTF
RefCounted.

Error message:
In file included from
  .../third_party/blink/renderer/core/style/style_navigation_index.cc:17:
.../third_party/blink/renderer/core/style/style_navigation_index.h:26:47:
  error: expected template-name before '<' token
.../third_party/blink/renderer/core/style/style_navigation_index.h:26:47:
  error: expected '{' before '<' token
.../third_party/blink/renderer/core/style/style_navigation_index.h:26:47:
  error: expected unqualified-id before '<' token
.../third_party/blink/renderer/core/style/style_navigation_index.cc:21:44:
  error: invalid use of incomplete type 'class blink::StyleNavigationIndex'

:Testing Performed:
Build done without jumbo build.

:QA Notes:
Test-cases: GT-23309

:Issues Addressed:
[PLAT-98660] Port patch: [open][upstreamable][css][spatial_nav] CSS3
             navigation implementation

Change-Id: If9929ad827586a812732c50acdf25052c1746515
Reviewed-on: http://gpro.lge.com/c/webosose/chromium79/+/268681
Reviewed-by: OSE Helper Bot <ose@lge.com>
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>