[op][n_upsable][media] Add use_neva_media for mojom media session
:Release Notes:
Add use_neva_media for mojom media session for fixing compilation
errors in qemux86 and qemux86-64 builds

:Detailed Notes:
There is compilation error in qemux86 and qemux86-64 builds since
neva-media is not enabled for these builds. As a result we get
below compilation error:
  web_contents_user_data.h:40:61: error: invalid new-expression of
  abstract class type 'content::MediaSessionImpl'
  media_session_impl.h:76:7: note: because the following virtual
  functions are pure within 'content::MediaSessionImpl':
  media_session.mojom.h:212:16: note:
  'virtual void media_session::mojom::MediaSession::SetMuted(bool)'

With this change we keep SetMuted as open for all platforms

:Testing Performed:
Triggered GPVB build and checked there is no compilation errors

:QA Notes:
Test-cases: NA

:Issues Addressed:
[PLAT-116626] Handle mute event in the SystemMediaControlsWebos::HandleMediaKeyEventInternal

Change-Id: Ia7e579a29b533be461ced300864fcc811dabc155
Originally-Reviewed-on: http://gpro.lge.com/285341
Reviewed-on: http://gpro.lge.com/c/webosose/chromium79/+/285378
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Pankaj Maharana <pankaj.maharana@lge.com>
Reviewed-by: Praveen Kumar P <praveen.p@lge.com>
Reviewed-by: Youngsoo Choi <youngsoo.choi@lge.com>
Tested-by: Pankaj Maharana <pankaj.maharana@lge.com>