[op][n_upsable][css] Revert CSSStyleDeclaration setters fallback
:Release Notes:
Revert CSSStyleDeclaration setters fallback

:Detailed Notes:
After chromium74, CSSStyleDeclaration indexed access does not
provide setter access, breaking some applications, with this error:
TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported.

Though the new behavior is right, to keep legacy behavior we had to
revert the patch upstream. This means we need to update our
applications to be compatible with upstream new behavior.

Reverted patch is:
    commit 6eeb9ee0b0ce6d91c1c1e9451b2dde5a6a9b09a2
    Author: Yuki Shiino <yukishiino@chromium.org>
    Date:   Fri Feb 8 15:51:39 2019 +0000

    v8binding: Fix CSSStyleDeclaration's indexed setter not to fallback

    This is a quick fix to work around an issue reported at:
    https://github.com/webcompat/web-bugs/issues/25390

    This patch makes readonly indexed properties not fall back to
    named properties.  Coincidentally the condition only applies to
    CSSStyleDeclaration, where we have the issue above.

    Blink's implementation for indexed/named properties is outdated
    overall.  General fix should follow.

    Change-Id: I418eaf04c61ac3680ff3bc75710489b526e36100
    Reviewed-on: https://chromium-review.googlesource.com/c/1460588
    Commit-Queue: Hitoshi Yoshida <peria@chromium.org>
    Reviewed-by: Kentaro Hara <haraken@chromium.org>
    Reviewed-by: Hitoshi Yoshida <peria@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#630328}

:Testing Performed:
1. Open settings
2. Go to channels/channels tuning
3. Select automatic tuning, press START
Tuning should happen, and it should not show a black screen with the
described error in JS console.

:QA Notes:
Test-cases: GT-21111

:Issues Addressed:
[PLAT-101115] [chromium79] Channel Tuning fails

Change-Id: I2503378b2fc205c2dac36cc44aed520d522a3a61
Reviewed-on: http://gpro.lge.com/c/webosose/chromium79/+/269635
Reviewed-by: OSE Helper Bot <ose@lge.com>
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>