fixup! [op][upsable][touch][selection_handle] Add switch --hide-selection-handles
:Release Notes:
Fix build error after adding --hide-selection-handles

:Detailed Notes:
Fix this error that may happen (depending on the jumbo grouping) compiling
RenderWidgetHostViewAura:
| ./../../../../../../../../../../build/chromium79/src/content/browser/renderer_host/render_widget_host_view_aura.cc: In member function 'void content::RenderWidgetHostViewAura::CreateSelectionController()':
| ./../../../../../../../../../../build/chromium79/src/content/browser/renderer_host/render_widget_host_view_aura.cc:2451:21: error: 'kHideSelectionHandles' is not a member of 'switches'
|            switches::kHideSelectionHandles);
|                      ^~~~~~~~~~~~~~~~~~~~~

:Testing Performed:
Compilation finishes.

:QA Notes:
Test-cases: not required (compilation issue)

:Issues Addressed:

Change-Id: Id72a736dd1447bf6856025a8069a690d36046fe8
Reviewed-on: http://gpro.lge.com/c/webosose/chromium79/+/268099
Reviewed-by: OSE Helper Bot <ose@lge.com>
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>